version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    ports:
      - 3010:3000
    volumes:
      - .:/api
    networks:
     - my_network
    depends_on:
      - database
    container_name: golang-api
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=database'

  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=api
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=shop
      - MYSQL_ROOT_HOST=%
    container_name: mysql-db
    networks:
     - my_network
    ports:
      - 4306:3306
    volumes:
      - mysql-data:/var/lib/mysql 

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - 5003:80
    networks:
     - my_network
    environment:
      - 'PMA_HOST=mysql-db'
      - 'PMA_PORT=3306'
    container_name: phpmyadmin

# persisted storage
volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge